#!/opt/perl/bin/perl
use strict;
use AnyEvent::Impl::Perl;
use AnyEvent;
use Net::IRC3::Connection;
$Net::IRC3::Client::DEBUG = 1;

my $c = AnyEvent->condvar;

my $con = Net::IRC3::Connection->new;


my ($nick, $user, $real) = qw/BinDepp BinDepp depp/;

$con->reg_cb (irc_001 => sub {
   my ($con) = @_;
   $con->event ('welcome'); # emit a self defined event
});

# display all irc messages for debugging
$con->reg_cb ('irc_*' => sub { warn "DEBUG: " . join ('|', %{$_[1]}) . "\n"; });

# we register now a callback on our self defined event
$con->reg_cb (welcome => sub {
   my ($con) = @_;
   $con->send_msg (undef, "PRIVMSG", "Hi!!!", "elmex");
});

my $t;
$t = AnyEvent->timer (after => 10, cb => sub {
   $con->disconnect ("Timeout exceeded");
   undef $t;
});

# lets 
$con->reg_cb (
   connect => sub {
      my ($con, $err) = @_;
      if (defined $err) {
         warn "Connect ERROR! => $err\n";
         $c->broadcast;
      } else {
         warn "Connected! Yay!\n";
      }

      # send IRC registration
      $con->send_msg (undef, "NICK", undef, $nick);
      $con->send_msg (undef, "USER", $real || $nick, $user || $nick, "*", "0");
   },
   disconnect => sub {
      warn "Oh, got a disconnect: $_[1], exiting...\n";
      $c->broadcast;
   }
);

$con->connect ("localhost", 6667);

$c->wait;
